/**
 * ⚠️ 自动生成，请勿手改。
 * 重新生成：npm run icons:thin
 *
 * lucide 兜底图标等宽包装：把描边统一到 XIMO_STROKE（${XIMO_STROKE}），
 * 与 Ximo 自绘字形混排时粗细一致。
 */
import { forwardRef } from 'react'
import * as L from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'
import { XIMO_STROKE } from './stroke'

function thin(Cmp: LucideIcon): LucideIcon {
  const W = forwardRef<SVGSVGElement, LucideProps>(function ThinIcon(props, ref) {
    return <Cmp ref={ref} strokeWidth={XIMO_STROKE} {...props} />
  })
  W.displayName = `${Cmp.displayName ?? 'LucideIcon'}·thin`
  return W as unknown as LucideIcon
}

export const Activity = thin(L.Activity)
export const AlignLeft = thin(L.AlignLeft)
export const ArrowDownWideNarrow = thin(L.ArrowDownWideNarrow)
export const ArrowUpDown = thin(L.ArrowUpDown)
export const ArrowUpNarrowWide = thin(L.ArrowUpNarrowWide)
export const BarChart3 = thin(L.BarChart3)
export const Bolt = thin(L.Bolt)
export const BookOpen = thin(L.BookOpen)
export const Bookmark = thin(L.Bookmark)
export const Bug = thin(L.Bug)
export const Calendar = thin(L.Calendar)
export const CalendarDays = thin(L.CalendarDays)
export const Camera = thin(L.Camera)
export const CheckCircle = thin(L.CheckCircle)
export const CheckSquare = thin(L.CheckSquare)
export const Circle = thin(L.Circle)
export const Clipboard = thin(L.Clipboard)
export const ClipboardCheck = thin(L.ClipboardCheck)
export const Code = thin(L.Code)
export const Coins = thin(L.Coins)
export const Columns = thin(L.Columns)
export const CornerDownRight = thin(L.CornerDownRight)
export const Database = thin(L.Database)
export const Droplets = thin(L.Droplets)
export const EyeOff = thin(L.EyeOff)
export const File = thin(L.File)
export const FileCheck = thin(L.FileCheck)
export const FileCode = thin(L.FileCode)
export const FileCode2 = thin(L.FileCode2)
export const FileDiff = thin(L.FileDiff)
export const FileEdit = thin(L.FileEdit)
export const FileJson = thin(L.FileJson)
export const FilePlus = thin(L.FilePlus)
export const Film = thin(L.Film)
export const Filter = thin(L.Filter)
export const FlaskConical = thin(L.FlaskConical)
export const Folder = thin(L.Folder)
export const FolderInput = thin(L.FolderInput)
export const FolderPlus = thin(L.FolderPlus)
export const FolderSearch = thin(L.FolderSearch)
export const FolderTree = thin(L.FolderTree)
export const Gauge = thin(L.Gauge)
export const GitCompare = thin(L.GitCompare)
export const GripVertical = thin(L.GripVertical)
export const Hand = thin(L.Hand)
export const Hash = thin(L.Hash)
export const Home = thin(L.Home)
export const Image = thin(L.Image)
export const Inbox = thin(L.Inbox)
export const Infinity = thin(L.Infinity)
export const KanbanSquare = thin(L.KanbanSquare)
export const Keyboard = thin(L.Keyboard)
export const Layout = thin(L.Layout)
export const LayoutDashboard = thin(L.LayoutDashboard)
export const LayoutGrid = thin(L.LayoutGrid)
export const LayoutPanelTop = thin(L.LayoutPanelTop)
export const Library = thin(L.Library)
export const Lightbulb = thin(L.Lightbulb)
export const Link = thin(L.Link)
export const Link2 = thin(L.Link2)
export const List = thin(L.List)
export const ListChecks = thin(L.ListChecks)
export const ListFilter = thin(L.ListFilter)
export const ListOrdered = thin(L.ListOrdered)
export const ListTodo = thin(L.ListTodo)
export const ListTree = thin(L.ListTree)
export const Lock = thin(L.Lock)
export const LogOut = thin(L.LogOut)
export const Mail = thin(L.Mail)
export const Maximize2 = thin(L.Maximize2)
export const Menu = thin(L.Menu)
export const MessageCircle = thin(L.MessageCircle)
export const MessageSquareText = thin(L.MessageSquareText)
export const MessagesSquare = thin(L.MessagesSquare)
export const Mic = thin(L.Mic)
export const Minimize2 = thin(L.Minimize2)
export const MousePointer2 = thin(L.MousePointer2)
export const Network = thin(L.Network)
export const Package = thin(L.Package)
export const PanelRightClose = thin(L.PanelRightClose)
export const PanelRightOpen = thin(L.PanelRightOpen)
export const Pin = thin(L.Pin)
export const Power = thin(L.Power)
export const Puzzle = thin(L.Puzzle)
export const Radio = thin(L.Radio)
export const Redo2 = thin(L.Redo2)
export const Rocket = thin(L.Rocket)
export const RotateCw = thin(L.RotateCw)
export const Save = thin(L.Save)
export const Scissors = thin(L.Scissors)
export const SearchCheck = thin(L.SearchCheck)
export const SearchCode = thin(L.SearchCode)
export const Share2 = thin(L.Share2)
export const Shield = thin(L.Shield)
export const ShieldCheck = thin(L.ShieldCheck)
export const Sliders = thin(L.Sliders)
export const Smartphone = thin(L.Smartphone)
export const Store = thin(L.Store)
export const Table = thin(L.Table)
export const Tag = thin(L.Tag)
export const Target = thin(L.Target)
export const ToggleLeft = thin(L.ToggleLeft)
export const TrendingUp = thin(L.TrendingUp)
export const TriangleAlert = thin(L.TriangleAlert)
export const Unlink = thin(L.Unlink)
export const User = thin(L.User)
export const Volume2 = thin(L.Volume2)
export const Wand2 = thin(L.Wand2)
export const Webhook = thin(L.Webhook)
export const Workflow = thin(L.Workflow)
